config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "crops#index"
  resources :tops, only: [:index]

  resources :crops do
    resources :purchases, only: [:index, :create]
    resources :messages, only: [:create, :destroy, :edit, :update]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show] do
    resources :addresses, only: [:new, :create, :edit, :update, :index ]
    resources :goods, only: [:index]
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
    @crops = Crop.includes(:user).order('created_at DESC')
  end

  
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Culnoka</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <% if user_signed_in? %>
                <div> <%= link_to current_user.nickname, user_path(current_user.id), class: "navbar-brand-name" %> </div>
                <div> <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "navbar-brand" %></div>
                <% else %>
                <div> <%= link_to 'ログイン', new_user_session_path, class: "navbar-brand" %></div>
                <div> <%= link_to '新規登録', new_user_registration_path, class: "navbar-brand" %></div>
                <% end %>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"> <%= link_to "TOP PAGE", root_path, class: "nav-link" %> </li>
                        <li class="nav-item"><%= link_to '作物購入・出品', crops_path, class: "nav-link" %></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Header-->
        <header class="bg-top py-5" >
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">カルノーカ</h1>
                    <p class="lead fw-normal text-white-50 mb-0">余ったものを出品しよう</p>
                </div>
            </div>
        </header>

<%= form_with(url: search_crops_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <% @crops.each do |crop| %>
                        <div class="col mb-5">
                            <%= link_to crop_path(crop.id) do %>
                            <div class="card h-100">
                            
                            <!-- Product image-->
                            <%= image_tag crop.images[0], class: "card-img-top" %>
                            <!-- Product details-->
                            
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"> <%= crop.item_name %> </h5>
                                    <!-- Product price-->
                                    <span><%= crop.price %>円<br><%= crop.delivery_cost.name %></span>
                                </div>
                            </div>
                            <!-- Product actions-->

                            </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </section>





        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; mm_hm 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <%#script src="js/scripts.js"></script%>
    </body>
</html>