config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "crops#index"
  resources :tops, only: [:index]

  resources :crops do
    resources :purchases, only: [:index, :create]
    resources :messages, only: [:create, :destroy, :edit, :update]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show] do
    resources :addresses, only: [:new, :create, :edit, :update, :index ]
    resources :goods, only: [:index]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
  has_many :addresses
  has_many :crops
  has_many :purchases
  has_many :messages

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :level

  with_options numericality: { other_than: 0, message: 'Select' } do
    validates :level_id
  end

  with_options format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'include both letters and numbers' } do
    validates :password
  end

  with_options presence: true do
    validates :nickname
    validates :birthday
    validates :level_id
  end

    with_options uniqueness: { case_sensitive: true } do
      validates :nickname
      validates :email
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">メールアドレス</th>
            <td class="table__col2"><%= @user.email %></td>
          </tr>
          <tr>
            <th class="table__col1">誕生日</th>
            <td class="table__col2"><%= @user.birthday %></td>
          </tr>
          <tr>
            <th class="table__col1">ユーザーの種類</th>
            <td class="table__col2"><%= @user.level.name %></td>
          </tr>
        </tbody>
      </table>
<p> </p>
<p> </p>
<p> </p>
      <li><%= link_to '出品作物の確認', user_goods_path(current_user.id),  class: "address-index" %></li>
    <% if current_user.id == @user.id %>
      <li><%= link_to '住所情報の投稿', new_user_address_path(current_user.id),  class: "address-post" %></li>
    <% if @user.addresses.present? %>
      <li><%= link_to '住所情報の確認', user_addresses_path(current_user.id),  class: "address-index" %></li>
    <% end %>
    <% end %>
    </div>
    <h3><%=link_to 'もどる', root_path, class:"btn-1" %></h3>
  </div>
</div>