config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "crops#index"
  resources :tops, only: [:index]

  resources :crops do
    resources :purchases, only: [:index, :create]
    resources :messages, only: [:create, :destroy, :edit, :update]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show] do
    resources :addresses, only: [:new, :create, :edit, :update, :index ]
    resources :goods, only: [:index]
  end
  
end

app/models/crop.rb
class Crop < ApplicationRecord

  belongs_to :user
  has_many :purchases
  has_many :messages, dependent: :destroy

  has_many_attached :images

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :delivery_cost
  belongs_to :prefecture
  belongs_to :delivery_time

  with_options presence: true do
    validates :images
    validates :item_name
    validates :explanation
    validates :price
  end

  with_options numericality: { other_than: 0, message: 'Select' } do
    validates :category_id
    validates :condition_id
    validates :delivery_cost_id
    validates :prefecture_id
    validates :delivery_time_id
  end

  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }
  validate :image_length, :image_size
  


  def self.search(search)
    if search != ""
      Crop.where('item_name LIKE(?)', "%#{search}%")
    else
      Crop.all
    end
  end


  private
  def image_length
    if images.length != 4
      errors.add(:images, "must exist 4")
    end
  end

  def image_size
    images.each do |image|
      if image.blob.byte_size > 2.megabytes
        errors.add(:images, "must be within 5MB of one file")
      end
    end
  end

end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_crop, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @crops = Crop.includes(:user).order('created_at DESC')
  end

  def new
    @crop = Crop.new
  end

  def create
    @crop = Crop.new(crop_params)
    if @crop.save
      redirect_to crops_path
    else
      render :new
    end
  end

  def show
    @message = Message.new
    @crop = Crop.find(params[:id])
    @messages = @crop.messages.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @crop.update(crop_params)
      redirect_to crop_path
    else
      render :edit
    end
  end

  def destroy
    @crop.destroy
    redirect_to root_path
  end

  def search
    @crops = Crop.search(params[:keyword])
  end


  private

  def crop_params
    params.require(:crop).permit(:item_name, :explanation, :category_id, :condition_id, :delivery_cost_id, :prefecture_id,
                                 :delivery_time_id, :price, :discontinued, images: []).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index if (current_user.id != @crop.user_id)
  end

  def set_crop
    @crop = Crop.find(params[:id])
  end


end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/edit.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">作物の情報を入力</h2>

    <%= form_with model: @crop, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object =%>
    
    <div class="img-upload">
      <div class = "img-upload-text">
        <div class="weight-bold-text">
          出品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <div class="file-up">
            クリックorドラッグ&ドロップで画像ファイルを４枚アップロード
          </div>
      </div>

      <div class = "sell-container__content__upload__items__box">
        <ul id="output-box">
          <div id="image-input", tabindex:"0" >
            <%= f.label :images, for: "item_images0", class: 'sell-container__content__upload__items__box__label ', data: {label_id: 0} do %>
              <%= f.file_field :images, multiple: true, class: ' dropzone drop-item', name: 'crop[images][]', id: "item_images0" %>
            <% end %>
          <div >
        </ul>
      </div>
    </div>
  </div>


    <div class="new-items">
      <div class="weight-bold-text">
        作物名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"作物名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          作物の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"作物の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">作物の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          作物の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">非売、販売の選択</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.radio_button :discontinued, 0, checked: true %>
        <%= f.label :discontinued, "販売品", {value: 0, style: "display: inline-block;"} %>
        <%= f.radio_button :discontinued, 1 %>
        <%= f.label :discontinued, "非売品/売切れ品", {value: 1, style: "display: inline-block;"} %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">非売時必須</span>
        </div>
        <%= f.collection_select(:delivery_cost_id, DeliveryCost.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">非売時必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">非売時必須</span>
        </div>
        <%= f.collection_select(:delivery_time_id, DeliveryTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">非売時必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (5%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>

    <div class="caution">
      <p class="sentence">
        加工食品の販売には保健所、
        有機野菜としての販売は有機JASの認証が必要です。
        無許可での加工食品、および有機野菜としての販売は
        法令違反であり処罰される可能性があります。
      </p>
      <p class="sentence">
        出品をもちまして
        利用規約に同意したことになります。
      </p>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>
</div>

app/views/crops/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Culnoka</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%#link href="css/styles.css" rel="stylesheet" /%>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <% if user_signed_in? %>
                <div> <%= link_to current_user.nickname, user_path(current_user.id), class: "navbar-brand-name" %> </div>
                <div> <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "navbar-brand" %></div>
                <% else %>
                <div> <%= link_to 'ログイン', new_user_session_path, class: "navbar-brand" %></div>
                <div> <%= link_to '新規登録', new_user_registration_path, class: "navbar-brand" %></div>
                <% end %>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <%
=begin%>
 <li class="nav-item"> <%= link_to "TOP PAGE", root_path, class: "nav-link" %> </li>
                        <li class="nav-item"><%= link_to '作物購入・出品', crops_path, class: "nav-link" %></li>
                        <li class="nav-item dropdown">
                        </li> 
<%
=end%>
                    </ul>


                </div>
            </div>
        </nav>


        <!-- Header-->
        <header class="bg-crop py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">作物市場</h1>
                    <p class="lead fw-normal text-white-50 mb-0">作物を出品してみよう</p>
                </div>
            </div>
        </header>


        <%
=begin%>
 <% if current_user.level.id > 5 %> 
<%
=end%>
        <%= link_to '作物を出品する', new_crop_path, class: "btn-1" %>
        <%
=begin%>
 <% end %> 
<%
=end%>

<%= form_with(url: search_crops_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <% @crops.each do |crop| %>
                        <div class="col mb-5">
                            <%= link_to crop_path(crop.id) do %>
                            <div class="card h-100">
                            
                            <!-- Product image-->
                            <div class="card-img-top", style="background-image: url(<%= rails_blob_path(crop.images[0])%>)">
                            </div>
                            <!-- Product details-->
                            
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"> <%= crop.item_name %> </h5>
                                    <!-- Product price-->
                                    <span><%= crop.price %>円<br><%= crop.delivery_cost.name %></span>
                                    
                                </div>
                            </div>
                            <!-- Product actions-->

                            </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </section>





        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; mm_hm 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <%#script src="js/scripts.js"></script%>
    </body>
</html>

app/views/crops/search.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Culnoka</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%#link href="css/styles.css" rel="stylesheet" /%>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <% if user_signed_in? %>
                <div> <%= link_to current_user.nickname, user_path(current_user.id), class: "navbar-brand-name" %> </div>
                <div> <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "navbar-brand" %></div>
                <% else %>
                <div> <%= link_to 'ログイン', new_user_session_path, class: "navbar-brand" %></div>
                <div> <%= link_to '新規登録', new_user_registration_path, class: "navbar-brand" %></div>
                <% end %>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"> <%= link_to "TOP PAGE", root_path, class: "nav-link" %> </li>
                        <li class="nav-item"><%= link_to '作物購入', crops_path, class: "nav-link" %></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>


        <!-- Header-->
        <header class="bg-crop py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">作物市場</h1>
                    <p class="lead fw-normal text-white-50 mb-0">作物を出品してみよう</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <% if user_signed_in? %>
        <% if current_user.level.id > 5 %>
        <%= link_to '作物を出品する', new_crop_path, class: "btn-1" %>
        <% end %>
        <% end %>

<%= form_with(url: search_crops_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <% @crops.each do |crop| %>
                        <div class="col mb-5">
                            <%= link_to crop_path(crop.id) do %>
                            <div class="card h-100">
                            
                            <!-- Product image-->
                            <%= image_tag crop.images[0], class: "card-img-top" %>
                            <!-- Product details-->
                            
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"> <%= crop.item_name %> </h5>
                                    <!-- Product price-->
                                    <span><%= crop.price %>円<br><%= crop.delivery_cost.name %></span>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                            </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </section>





        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; mm_hm 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <%#script src="js/scripts.js"></script%>
    </body>
</html>

app/views/crops/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%#link href="css/styles.css" rel="stylesheet" /%>
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">カルノーカ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!"></a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->

        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class='imagesContainer'>
                    <div class='showMainImage', id='mainImage', style="background-image: url(<%= rails_blob_path(@crop.images[0])%>)">
                    </div>
                    <ul class="subImagesContainer">
                        <% @crop.images.each_with_index do |image, i| %>
                            <div class='subImage', style="background-image: url(<%= rails_blob_path(@crop.images[i])%>)">
                            </div>
                        <% end %>
                    </ul>
                </div>
                    <div class="col-lg-5">
                        <h1 class="font-weight-light"><%= @crop.item_name %></h1>
                        <p><%= @crop.explanation %></p>
                        <% if @crop.discontinued == false %>
                        <p>産地: <%= @crop.prefecture.name %></p>
                        <p>状態: <%= @crop.condition.name %></p>
                        <p>値段: <%= @crop.price %>円,   輸送費: <%=@crop.delivery_cost.name %></p>
                        <p>到着日数: <%=@crop.delivery_time.name %></p> 
                        <% end %>
                        <p>出品者: <%= link_to @crop.user.nickname, user_path(@crop.user.id) %></p>
                        <% if user_signed_in? %>
                        <% if current_user.id != @crop.user.id %>
                        <% if @crop.discontinued == false %>
                        <% if current_user.addresses.present? %>
                        <%= link_to "購入画面に進む", crop_purchases_path(@crop.id) ,class:"btn btn-1"%>
                        <% else %>
                        <br>
                        購入する際には、最初に住所登録をしていただく必要があります。<br>
                        <br>
                        住所登録はトップページ→自身のニックネームクリックした先の<br>
                        マイページ内にあります。
                        <% end %>
                        <% end %>
                        <% end %>
                        <% end %>
                        <%= link_to "戻る", crops_path ,class:"btn btn-1"%>
                    </div>
                </div>
                <% if user_signed_in? %>
                <% if current_user.id == @crop.user.id %>
                <%= link_to "削除", crop_path, method: :delete, class:"btn btn-1"%>
                <%= link_to "作物の編集", edit_crop_path, method: :get, class:"btn btn-1"%>
                <% end %>
                <% end %>
        </div>
    

  <div class="input-message">
    <% if user_signed_in? %>
      <%= form_with(model: [@crop, @message], local: true) do |f| %>
    <div class="img-upload">
      <strong ><p class=comment-form>コメントフォーム</p>
      </strong>

      <div class="weight-bold-text">
        投稿画像
        <span class="indispensable">どちらか必須</span>
      </div>

      <div class=" click-upload">
        <p>
          クリックorドラッグ&ドロップで
          <br>画像ファイルを1枚アップロード
          <br>
          <br>差替時は再度クリックorドラッグ&ドロップ
        </p>
        <div class='message-input', id='message-input'>
        <%= f.file_field :image,  class:" dropzone message-image-input"  %>
        </div>
      </div>

      <div class="weight-bold-text">
        コメント
      <span class="indispensable">どちらか必須</span>
      </div>
        <%= f.text_area :comment, class:"message-text", id:"item-info", placeholder:"コメント(120字以内)" ,rows:"7" ,maxlength:"120" %>
        <%= f.submit "SEND" %>
    </div>
      <% end %>

    <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
        </strong>
    <% end %>
    
  </div>


    <div class="messages">
      <h4>＜コメント一覧＞</h4>
      <% @messages.each do |message| %>
        <div class="messages-content">
          <strong><%= link_to message.user.nickname, "/users/#{message.user_id}", class: 'message-name' %></strong>
          <%= image_tag message.image.variant(resize: '250x250'),  class: 'message-image' if message.image.attached? %>
          <%= message.comment %>
          <% if current_user.id == message.user.id %>
          <%= link_to "削除", crop_message_path(@crop, message), method: :delete %>
          <%= link_to "編集", edit_crop_message_path(@crop, message), method: :get %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>


        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; mm_hm 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <%#script src="js/scripts.js"></script%>
    </body>
</html>