config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "crops#index"
  resources :tops, only: [:index]

  resources :crops do
    resources :purchases, only: [:index, :create]
    resources :messages, only: [:create, :destroy, :edit, :update]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show] do
    resources :addresses, only: [:new, :create, :edit, :update, :index ]
    resources :goods, only: [:index]
  end
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update]
  before_action :set_address_index, only: [:index]
  before_action :move_to_index, only: [:edit, :update, :index]

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def index
    @address = Address.where(user_id: params[:user_id])
    @user = User.find_by(id: params[:user_id])
  end

end


private
def address_params
  params.require(:address).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :zip_code, :prefecture_id, :city, :addresses, :building,
    :phone_no).merge(user_id: current_user.id)
end

def set_address
  @address = Address.find(params[:id])
  @address_mono = Address.find_by(user_id: params[:user_id])
end

def set_address_index
  @address_mono = Address.find_by(user_id: params[:user_id])
end

def move_to_index
  redirect_to root_path if (current_user.id != @address_mono.user_id)
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/edit.html.erb
<%= form_with model: @address, url: user_address_path(current_user.id, @address.id), class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      配達先情報入力
    </h1>
  </div>
    <%= render 'shared/error_messages', model: f.object =%>
  <div class="form-group">
    <div class='form-text-wrap'>

  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">本名(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">本名カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">会社・店舗名</label>
      <span class="indispensable">任意</span>
    </div>
    <%= f.text_area :business_name, class:"input-default", id:"nickname", placeholder:"例) 株式会社ノーカ", maxlength:"40" %>
  </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :zip_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id,  Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :addresses, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_no, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>


    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
    
  <div class='register-btn'>
    <%= f.submit "住所登録" ,class:"register-red-btn" %>
  </div>
  <%=link_to 'もどる', user_addresses_path, class:"back-btn-regist" %>
  </div>
<% end %>

app/views/addresses/index.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報" %>
      </h2>
      <% @address.each_with_index do |address, idx| %>
      <h3>住所<%= idx + 1 %> </h3>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">姓</th>
            <td class="table__col2"><%= address.first_name %></td>
          </tr>
          <tr>
            <th class="table__col1">姓(カナ)</th>
            <td class="table__col2"><%= address.first_name_kana %></td>
          </tr>
          <tr>
            <th class="table__col1">名</th>
            <td class="table__col2"><%= address.last_name %></td>
          </tr>
          <tr>
            <th class="table__col1">名(カナ)</th>
            <td class="table__col2"><%= address.last_name_kana %></td>
          </tr>
          <tr>
            <th class="table__col1">法人名</th>
            <td class="table__col2"><%= address.business_name %></td>
          </tr>
          <tr>
            <th class="table__col1">郵便番号</th>
            <td class="table__col2"><%= address.zip_code %></td>
          </tr>
          <tr>
            <th class="table__col1">都道府県 </th>
            <td class="table__col2"><%= address.prefecture.name %></td>
          </tr>
          <tr>
            <th class="table__col1">市町村</th>
            <td class="table__col2"><%= address.city %></td>
          </tr>
            <th class="table__col1">番地</th>
            <td class="table__col2"><%= address.addresses %></td>
          </tr>
            <th class="table__col1">建物名</th>
            <td class="table__col2"><%= address.building %></td>
          </tr>
            <th class="table__col1">電話番号</th>
            <td class="table__col2"><%= address.phone_no %></td>
        </tbody>
        <%= link_to '住所情報の編集', edit_user_address_path(current_user.id, address.id),  class: "address-edit" %>
      </table>
      <% end %>
      <%=link_to 'もどる', user_path(current_user.id), class:"btn-1" %>

app/views/addresses/new.html.erb
<%= form_with model: @address, url: user_addresses_path(current_user.id), class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      配達先情報入力
    </h1>
  </div>
    <%= render 'shared/error_messages', model: f.object =%>
  <div class="form-group">
    <div class='form-text-wrap'>

  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">本名(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">本名カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">会社・店舗名</label>
      <span class="indispensable">任意</span>
    </div>
    <%= f.text_area :business_name, class:"input-default", id:"nickname", placeholder:"例) 株式会社ノーカ", maxlength:"40" %>
  </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :zip_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id,  Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :addresses, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_no, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>


    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
    
  <div class='register-btn'>
  <%= f.submit "住所登録" ,class:"register-red-btn" %>
  </div>
  <%=link_to 'もどる', user_path(current_user.id), class:"back-btn-regist" %>
  </div>
<% end %>